config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'locations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :my_location
  after_validation :geocode


  def my_location
    "#{address}, #{city}, GA"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  include ApplicationHelper

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @buses = HTTParty.get('http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus')

    @bus_count = 0

    @nearby_buses = []

    @buses.each do |bus|
      if nearby(@location.longitude, @location.latitude, bus["LONGITUDE"].to_f, bus["LATITUDE"].to_f)
        @bus_count += 1
        @nearby_buses.push(bus)
      end
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :city, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def nearby(mylng, mylat, buslng, buslat)
  if (mylng - buslng).abs <= 0.01 && (mylat - buslat).abs <= 0.01
    return true
  else
    return false
  end
end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MartaNearMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['google_api_key']}" %>
  </head>

  <body>
    <div class="container">

    <%= yield %>


    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: @location, local: true) do |form| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, placeholder: "Approximate location" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, placeholder: "City" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>Is a Bus nearby?</h1>

<p>Enter your location (<em>I'm at the corner of ...</em>), and we will let you know if there is a bus in your vicinity</p>

<%= render 'form' %>

app/views/locations/show.html.erb
<p id="notice"> <%= notice %> </p>

<h2>You are currently standing at...</h2>

<p><%= @location.my_location %> </p>

<h2>The closest buses are...</h2>

<% if @bus_count == 0 %>

<p>...not really that close, try calling an uber or start walking</p>

<% end %>

<% @nearby_buses.each_with_index do |bus, index| %>
<p>
  <strong>Route:</strong><%= bus["ROUTE"] %> <br>
  <strong>Vehicle:</strong> <%= bus["ROUTE"] %> <br>
  <strong>Next Stop:</strong><%= bus["TIMEOUT"] %> <br>
</p>


<script>
    function initialize(){
      var userCoords = new google.maps.LatLng(<%= @location.latitude %>, <%= @location.longitude %>);

      var busCoords = new google.maps.LatLng(<%= bus ["LATITUDE"] %>, <%= bus ["LONGITUDE"] %>);

      var mapOptions ={
        center: userCoords,
        zoom: 12,
        scrollwheel: false
      };

      var map = new google.maps.Map(document.getElementById('map-canvas<%= index %>'), mapOptions);

      var coords = [userCoords, busCoords];

      var marker= new google.maps.Marker ({
        position: busCoords,
        map: map,
        animation: google.maps.Animation.DROP
      });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div class="bus-map" id="map-canvas<%= index %>" style="height: 200px; width:200px"> </div>

<% end %>